title: "Welcome to OpenSourcePackages"
theme: jekyll-theme-minimal
description: >
  A collection of open-source packages and resources for industry and academic use.
logo: "https://raw.githubusercontent.com/jonathanatuscpsu/Business-Programming/main/Python_66.png"
show_downloads: false

github:
  is_project_page: true

color_mode:
  default: auto
  toggle: true

sass:
  style: compressed
